inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'exe/**/*'
    - 'examples/**/*'

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
