inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'exe/**/*'
    - 'examples/**/*'

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/CommandLiteral:
  Enabled: false
